{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cmo.fullname" . }}
  labels:
    {{- include "cmo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cmo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
        - podSelector:
            matchLabels:
              cache-me-outside.io/client: "true"
      ports:
        - port: 6379
        - port: 16379
        - port: 26379
        {{- if .Values.metrics.exporter.enabled }}
        - port: {{ .Values.metrics.exporter.port }}
        {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
