apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmo.headless" . }}
  labels:
    {{- include "cmo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "cmo.selector" (merge (dict "component" "data") .) | nindent 4 }}
  ports:
    - name: client
      port: 6379
      targetPort: client
    - name: bus
      port: 16379
      targetPort: bus
---
{{- if ne .Values.topology "sentinel" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmo.fullname" . }}
  labels:
    {{- include "cmo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cmo.selector" (merge (dict "component" "data") .) | nindent 4 }}
  ports:
    - name: client
      port: 6379
      targetPort: client
{{- end }}
{{- if eq .Values.topology "sentinel" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmo.fullname" . }}-sentinel
  labels:
    {{- include "cmo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cmo.selector" (merge (dict "component" "sentinel") .) | nindent 4 }}
  ports:
    - name: sentinel
      port: 26379
      targetPort: sentinel
{{- end }}
