#!/usr/bin/env bash
# Move slots off a primary, then delete the node. A replica is deleted directly.
# A primary that still has replicas is refused; remove those replicas first.
#   ./cluster-remove.sh cache-me-outside-cluster-3
set -euo pipefail

cd "$(dirname "$0")"
# shellcheck disable=SC1091
source ./lib.sh
cmo_load_env

name="${1:-}"
if [[ -z "$name" ]]; then
    echo "Usage: ./cluster-remove.sh <container>" >&2
    exit 1
fi
state_file="$(cmo_state_file)"
if [[ ! -f "$state_file" ]]; then
    echo "No cluster state." >&2
    exit 1
fi
# shellcheck disable=SC1090
source "$state_file"
if [[ "$topology" != "cluster" ]]; then
    echo "State is ${topology}, not cluster." >&2
    exit 1
fi

keeper=""
found=0
new_nodes=()
for spec in "${nodes[@]}"; do
    # shellcheck disable=SC2086
    set -- $spec
    if [[ "$1" == "$name" ]]; then
        found=1
        continue
    fi
    new_nodes+=("$spec")
    if [[ -z "$keeper" ]]; then
        keeper="$1"
    fi
done
if [[ "$found" -ne 1 ]]; then
    echo "${name} is not in the cluster state." >&2
    exit 1
fi
if [[ -z "$keeper" ]]; then
    echo "Refusing to remove the last node." >&2
    exit 1
fi

nodes_out="$(cmo_admin "$keeper" CLUSTER NODES)"
parsed="$(awk -v name="$name" '
    $2 ~ ("(^|,)" name "([:,]|$)") {
        slots = 0
        for (i = 9; i <= NF; i++) {
            if ($i ~ /^[0-9]+-[0-9]+$/) {
                split($i, r, "-")
                slots += r[2] - r[1] + 1
            } else if ($i ~ /^[0-9]+$/) {
                slots++
            }
        }
        kind = ($3 ~ /master/ ? "primary" : "replica")
        print $1, kind, slots
        exit
    }' <<< "$nodes_out")"
if [[ -z "$parsed" ]]; then
    echo "CLUSTER NODES has no entry for ${name}." >&2
    exit 1
fi
read -r node_id kind slots <<< "$parsed"

if [[ "$kind" == "primary" ]]; then
    masters="$(awk '$3 ~ /master/ { c++ } END { print c+0 }' <<< "$nodes_out")"
    if ((masters < 2)); then
        echo "Refusing to remove the last primary." >&2
        exit 1
    fi
    replicas="$(awk -v id="$node_id" '$3 ~ /slave/ && $4 == id { c++ } END { print c+0 }' <<< "$nodes_out")"
    if ((replicas > 0)); then
        echo "${name} still has ${replicas} replica(s). Remove those first." >&2
        exit 1
    fi
    if ((slots > 0)); then
        dest="$(awk -v id="$node_id" '$3 ~ /master/ && $1 != id { print $1; exit }' <<< "$nodes_out")"
        if [[ -z "$dest" ]]; then
            echo "No other primary to receive slots." >&2
            exit 1
        fi
        cmo_cluster_mgr "$keeper" reshard "${keeper}:6379" \
            --cluster-from "$node_id" --cluster-to "$dest" \
            --cluster-slots "$slots" --cluster-yes
        left="$slots"
        for _i in $(seq 1 60); do
            left="$(cmo_admin "$keeper" CLUSTER NODES | awk -v name="$name" '
                $2 ~ ("(^|,)" name "([:,]|$)") {
                    slots = 0
                    for (i = 9; i <= NF; i++) {
                        if ($i ~ /^[0-9]+-[0-9]+$/) {
                            split($i, r, "-")
                            slots += r[2] - r[1] + 1
                        } else if ($i ~ /^[0-9]+$/) slots++
                    }
                    print slots
                    exit
                }')"
            if [[ "${left:-1}" == "0" ]]; then
                break
            fi
            sleep 1
        done
        if [[ "${left:-1}" != "0" ]]; then
            echo "${name} still owns ${left:-unknown} slots; not deleting it." >&2
            exit 1
        fi
    fi
    drained_primary=1
else
    drained_primary=0
fi

cmo_cluster_mgr "$keeper" del-node "${keeper}:6379" "$node_id" --cluster-yes

{
    echo "# Generated by cluster-remove.sh. Do not commit."
    echo "topology=cluster"
    echo "cluster_replicas=${cluster_replicas:-0}"
    echo "nodes=("
    for spec in "${new_nodes[@]}"; do
        printf '  "%s"\n' "$spec"
    done
    echo ")"
} > "$state_file"

# Keep the membership just written. A caller may still have CMO_RESET_TOPOLOGY=1
# from the initial ./up.sh cluster.
CMO_RESET_TOPOLOGY=0 ./render-topology.sh cluster
# Remove only this container. `compose up --remove-orphans` would also delete
# a standalone service that shares the project.
docker rm -f "$name" >/dev/null
cmo_dc -f "$(cmo_compose_file)" up -d --no-build
docker volume rm "${name}-data" >/dev/null 2>&1 || true

if [[ "$drained_primary" -eq 1 ]]; then
    # The reshard above moved every slot onto one primary. Spread them again.
    cmo_cluster_mgr "$keeper" rebalance "${keeper}:6379" \
        --cluster-use-empty-primaries --cluster-yes
fi
echo "removed ${name}"
