#!/usr/bin/env bash
# Add a live cluster node and, for a primary, rebalance slots onto it.
#   ./cluster-add.sh primary
#   ./cluster-add.sh replica cache-me-outside-cluster-0
set -euo pipefail

cd "$(dirname "$0")"
# shellcheck disable=SC1091
source ./lib.sh
cmo_load_env

role="${1:-}"
of="${2:--}"
case "$role" in
    primary) of="-" ;;
    replica)
        if [[ "$of" == "-" || -z "$of" ]]; then
            echo "Usage: ./cluster-add.sh replica <primary-container>" >&2
            exit 1
        fi
        ;;
    *)
        echo "Usage: ./cluster-add.sh primary | replica <primary-container>" >&2
        exit 1
        ;;
esac

state_file="$(cmo_state_file)"
if [[ ! -f "$state_file" ]]; then
    echo "No cluster is recorded. Start one with ./up.sh cluster." >&2
    exit 1
fi
# shellcheck disable=SC1090
source "$state_file"
if [[ "$topology" != "cluster" ]]; then
    echo "State is ${topology}, not cluster." >&2
    exit 1
fi

max_index=-1
max_port=$((CMO_HOST_PORT - 1))
keeper=""
found_of=0
for spec in "${nodes[@]}"; do
    # shellcheck disable=SC2086
    set -- $spec
    stem="$(cmo_member_name "cluster-")"
    index="${1#"$stem"}"
    if ((index > max_index)); then
        max_index="$index"
    fi
    if (( $4 > max_port )); then
        max_port="$4"
    fi
    if [[ -z "$keeper" && "$2" == "primary" ]]; then
        keeper="$1"
    fi
    if [[ "$role" == "replica" && "$1" == "$of" ]]; then
        if [[ "$2" != "primary" ]]; then
            echo "$of is not a primary in the state file." >&2
            exit 1
        fi
        found_of=1
    fi
done
if [[ "$role" == "replica" && "$found_of" -ne 1 ]]; then
    echo "No primary named ${of} is in the cluster state." >&2
    exit 1
fi

if [[ -z "$keeper" ]]; then
    echo "No primary is recorded." >&2
    exit 1
fi

next=$((max_index + 1))
name="$(cmo_member_name "cluster-${next}")"
port=$((max_port + 1))
bind="$CMO_BIND_ADDRESS"
cmo_refuse_wildcard_bind "$bind" CMO_BIND_ADDRESS
nodes+=("${name} ${role} ${of} ${port} ${bind}")

{
    echo "# Generated by cluster-add.sh. Do not commit."
    echo "topology=cluster"
    echo "cluster_replicas=${cluster_replicas:-0}"
    echo "nodes=("
    for spec in "${nodes[@]}"; do
        printf '  "%s"\n' "$spec"
    done
    echo ")"
} > "$state_file"

# Keep the membership just written. A caller may still have CMO_RESET_TOPOLOGY=1
# from the initial ./up.sh cluster.
CMO_RESET_TOPOLOGY=0 ./render-topology.sh cluster
cmo_dc -f "$(cmo_compose_file)" up -d --no-build --wait "$name"
cmo_wait_healthy "$name"

agree_names=()
for spec in "${nodes[@]}"; do
    # shellcheck disable=SC2086
    set -- $spec
    agree_names+=("$1")
done

if [[ "$role" == "replica" ]]; then
    primary_id="$(cmo_admin "$keeper" CLUSTER NODES | awk -v name="$of" '
        $3 ~ /master/ {
            if ($2 ~ ("(^|,)" name "([:,]|$)")) { print $1; exit }
        }')"
    if [[ -z "$primary_id" ]]; then
        echo "Could not find the node id for ${of}." >&2
        exit 1
    fi
    cmo_cluster_mgr "$keeper" add-node "${name}:6379" "${keeper}:6379" \
        --cluster-replica --cluster-primary-id "$primary_id" --cluster-yes
    cmo_wait_cluster_agreement "${#agree_names[@]}" "${agree_names[@]}"
    echo "added replica ${name} of ${of}"
else
    cmo_cluster_mgr "$keeper" add-node "${name}:6379" "${keeper}:6379" --cluster-yes
    cmo_wait_cluster_agreement "${#agree_names[@]}" "${agree_names[@]}"
    cmo_cluster_mgr "$keeper" rebalance "${keeper}:6379" \
        --cluster-use-empty-primaries --cluster-yes
    echo "added primary ${name} and rebalanced"
fi
