#!/usr/bin/env bash
# Write deploy/.generated/compose.yml for sentinel or cluster.
# Membership is deploy/.generated/state. Add and remove scripts update that
# file and render again. Passwords stay in deploy/.env.
set -euo pipefail

cd "$(dirname "$0")"
# shellcheck disable=SC1091
source ./lib.sh
cmo_load_env

requested="${1:-${CMO_TOPOLOGY:-sentinel}}"
case "$requested" in
    sentinel | cluster) ;;
    *)
        echo "render-topology.sh expects sentinel or cluster" >&2
        exit 1
        ;;
esac

cmo_refuse_wildcard_bind "${CMO_BIND_ADDRESS}" CMO_BIND_ADDRESS

gen_dir="$(cmo_generated_dir)"
mkdir -p "$gen_dir"
state="$gen_dir/state"

init_state() {
    local quorum i port bind n p
    bind="$CMO_BIND_ADDRESS"
    {
        echo "# Generated by render-topology.sh. Do not commit."
        echo "topology=${requested}"
        if [[ "$requested" == "sentinel" ]]; then
            if ((CMO_SENTINELS < 1 || CMO_REPLICAS < 1)); then
                echo "Sentinel topology needs at least 1 replica and 1 sentinel." >&2
                exit 1
            fi
            quorum=$(((CMO_SENTINELS / 2) + 1))
            if [[ -n "${CMO_SENTINEL_QUORUM:-}" ]]; then
                quorum="$CMO_SENTINEL_QUORUM"
            fi
            if ((quorum < 1 || quorum > CMO_SENTINELS)); then
                echo "Sentinel quorum ${quorum} is outside 1..${CMO_SENTINELS}." >&2
                exit 1
            fi
            echo "sentinel_count=${CMO_SENTINELS}"
            echo "sentinel_quorum=${quorum}"
            echo "sentinel_base_port=${CMO_SENTINEL_PORT}"
            echo "nodes=("
            echo "\"cmo-primary primary - ${CMO_HOST_PORT} ${bind}\""
            for i in $(seq 1 "$CMO_REPLICAS"); do
                port=$((CMO_HOST_PORT + i))
                echo "\"cmo-replica-${i} replica cmo-primary ${port} ${bind}\""
            done
            echo ")"
        else
            if ((CMO_CLUSTER_PRIMARIES < 3)); then
                echo "Cluster topology needs at least 3 primaries." >&2
                exit 1
            fi
            if ((CMO_CLUSTER_REPLICAS < 0)); then
                echo "CMO_CLUSTER_REPLICAS cannot be negative." >&2
                exit 1
            fi
            echo "cluster_replicas=${CMO_CLUSTER_REPLICAS}"
            echo "nodes=("
            n=0
            for i in $(seq 1 "$CMO_CLUSTER_PRIMARIES"); do
                port=$((CMO_HOST_PORT + n))
                echo "\"cmo-cluster-${n} primary - ${port} ${bind}\""
                n=$((n + 1))
            done
            for p in $(seq 0 $((CMO_CLUSTER_PRIMARIES - 1))); do
                for i in $(seq 1 "$CMO_CLUSTER_REPLICAS"); do
                    port=$((CMO_HOST_PORT + n))
                    echo "\"cmo-cluster-${n} replica cmo-cluster-${p} ${port} ${bind}\""
                    n=$((n + 1))
                done
            done
            echo ")"
        fi
    } > "$state"
}

if [[ "${CMO_RESET_TOPOLOGY:-0}" == "1" || ! -f "$state" ]]; then
    init_state
fi

# shellcheck disable=SC1090
source "$state"
if [[ "$topology" != "$requested" ]]; then
    echo "deploy/.generated/state is a ${topology} topology. Run ./down.sh or CMO_RESET_TOPOLOGY=1 ./up.sh ${requested}." >&2
    exit 1
fi

for spec in "${nodes[@]}"; do
    # name role of host_port bind
    # shellcheck disable=SC2086
    set -- $spec
    cmo_refuse_wildcard_bind "$5" "bind for $1"
done

compose="$gen_dir/compose.yml"
{
    echo "# Generated by deploy/render-topology.sh. Do not commit."
    echo "# Host ports are published on each node's bind address. The default is 127.0.0.1."
    echo
    echo "name: cache-me-outside"
    echo
    echo "services:"

    first=1
    for spec in "${nodes[@]}"; do
        # shellcheck disable=SC2086
        set -- $spec
        name="$1"
        role="$2"
        of="$3"
        host_port="$4"
        bind="$5"
        bus_port=$((host_port + 10000))
        runtime_role="$role"
        if [[ "$topology" == "cluster" ]]; then
            # Cluster create assigns replication. replicaof plus cluster-enabled will not start.
            runtime_role="cluster"
        fi

        echo "  ${name}:"
        echo "    image: cache-me-outside:local"
        if [[ "$first" -eq 1 ]]; then
            echo "    build:"
            echo "      context: .."
            echo "      dockerfile: Dockerfile"
            first=0
        fi
        cat <<YAML
    container_name: ${name}
    hostname: ${name}
    env_file:
      - path: \${CMO_ENV_FILE:-.env}
        required: false
    environment:
      CMO_ROLE: ${runtime_role}
      CMO_PORT: "6379"
      CMO_MAXMEMORY: \${CMO_MAXMEMORY:-256mb}
      CMO_MAXMEMORY_POLICY: \${CMO_MAXMEMORY_POLICY:-allkeys-lru}
      CMO_IO_THREADS: \${CMO_IO_THREADS:-1}
YAML
        if [[ "$topology" == "cluster" ]]; then
            cat <<YAML
      CMO_CLUSTER_ENABLED: "yes"
      CMO_ANNOUNCE_HOSTNAME: ${name}
      CMO_CLUSTER_NODE_TIMEOUT: \${CMO_CLUSTER_NODE_TIMEOUT:-5000}
YAML
        fi
        if [[ "$topology" == "sentinel" && "$role" == "replica" ]]; then
            cat <<YAML
      CMO_PRIMARY_HOST: ${of}
      CMO_PRIMARY_PORT: "6379"
YAML
        fi
        echo "    ports:"
        echo "      - \"${bind}:${host_port}:6379\""
        if [[ "$topology" == "cluster" ]]; then
            echo "      - \"${bind}:${bus_port}:16379\""
        fi
        cat <<YAML
    volumes:
      - ${name}-data:/data
    restart: unless-stopped
    init: true
    stop_grace_period: 20s
    security_opt:
      - no-new-privileges:true
    mem_limit: \${CMO_CONTAINER_MEMORY:-512m}
    cpus: "\${CMO_CPUS:-1.0}"
    networks:
      cmo: {}
YAML
        if [[ "${CMO_ATTACH_PROXY_NET:-0}" == "1" ]]; then
            echo "      proxy-net: {}"
        fi
        cat <<YAML
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
YAML
        if [[ "$topology" == "sentinel" && "$role" == "replica" ]]; then
            cat <<YAML
    depends_on:
      ${of}:
        condition: service_healthy
YAML
        fi
    done

    if [[ "$topology" == "sentinel" ]]; then
        for i in $(seq 1 "$sentinel_count"); do
            sport=$((sentinel_base_port + i - 1))
            sbind="${CMO_BIND_ADDRESS}"
            override="CMO_BIND_ADDRESS_SENTINEL_${i}"
            if [[ -n "${!override:-}" ]]; then
                sbind="${!override}"
                cmo_refuse_wildcard_bind "$sbind" "$override"
            fi
            cat <<YAML
  cmo-sentinel-${i}:
    image: cache-me-outside:local
    container_name: cmo-sentinel-${i}
    hostname: cmo-sentinel-${i}
    env_file:
      - path: \${CMO_ENV_FILE:-.env}
        required: false
    environment:
      CMO_ROLE: sentinel
      CMO_PORT: "${CMO_SENTINEL_PORT}"
      CMO_PRIMARY_HOST: cmo-primary
      CMO_PRIMARY_PORT: "6379"
      CMO_SENTINEL_MASTER: \${CMO_SENTINEL_MASTER:-cmo}
      CMO_SENTINEL_QUORUM: "${sentinel_quorum}"
      CMO_SENTINEL_DOWN_AFTER_MS: \${CMO_SENTINEL_DOWN_AFTER_MS:-5000}
      CMO_SENTINEL_FAILOVER_TIMEOUT: \${CMO_SENTINEL_FAILOVER_TIMEOUT:-60000}
      CMO_SENTINEL_PARALLEL_SYNCS: \${CMO_SENTINEL_PARALLEL_SYNCS:-1}
    ports:
      - "${sbind}:${sport}:${CMO_SENTINEL_PORT}"
    restart: unless-stopped
    init: true
    stop_grace_period: 10s
    security_opt:
      - no-new-privileges:true
    mem_limit: \${CMO_SENTINEL_MEMORY:-128m}
    cpus: "\${CMO_SENTINEL_CPUS:-0.25}"
    depends_on:
      cmo-primary:
        condition: service_healthy
    networks:
      cmo: {}
YAML
            if [[ "${CMO_ATTACH_PROXY_NET:-0}" == "1" ]]; then
                echo "      proxy-net: {}"
            fi
            cat <<YAML
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
YAML
        done
    fi

    echo
    echo "volumes:"
    for spec in "${nodes[@]}"; do
        # shellcheck disable=SC2086
        set -- $spec
        echo "  ${1}-data:"
        echo "    name: ${1}-data"
    done

    echo
    echo "networks:"
    echo "  cmo:"
    echo "    name: cache-me-outside"
    if [[ "${CMO_ATTACH_PROXY_NET:-0}" == "1" ]]; then
        echo "  proxy-net:"
        echo "    external: true"
        echo "    name: proxy-net"
    fi
} > "$compose"

echo "Wrote ${compose}"
