cmo_role: standalone
cmo_cluster_enabled: "no"
cmo_bind_address: 127.0.0.1
cmo_port: 6379
cmo_maxmemory: 256mb
cmo_maxmemory_policy: allkeys-lru
cmo_io_threads: 1
cmo_admin_user: admin
cmo_app_user: app
cmo_primary_host: ""
cmo_primary_port: 6379
cmo_announce_ip: ""
cmo_announce_port: 6379
cmo_announce_bus_port: 16379
cmo_cluster_node_timeout: 5000
cmo_form_cluster: false
cmo_cluster_replicas: 0
cmo_cluster_seed: ""
cmo_cluster_join_as: primary
cmo_cluster_primary_id: ""
cmo_deb_path: ""
cmo_environment_file: /etc/cache-me-outside/environment
cmo_service: cache-me-outside.service
